version: '3.8'

services:
  ds_template:
    build: .
    container_name: ds_template_container
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
